### ISSUE TITLE
'node_modules/linq-es2015/dist/linq.d.ts' is not a module.

### ISSUE THREAD

**Issue by WouterBos** [ENikS/LINQ#9]
When importing, I get the message "Error TS2306 File 'D:/XXX/node_modules/linq-es2015/dist/linq.d.ts' is not a module." I use the import like this: "import {asEnumerable, Range} from 'linq-es2015";"
Furthermore I have a list of messages like "Cannot find name 'iterable'".

I also tried to load the sources with "import {asEnumerable, Range} from "linq-es2015/src/linq.ts";". But then I get a "JsErrorScriptException (0x30001)" without being related to some specific file.

Error found in Visual Studio 2015

**Comment by ENikS** [comment]
You have to build with TSC 1.18.xx and set target to es2015. For sample look at configuration file

**Comment by WouterBos** [comment]
Ah! Thanks. I'm afraid that in that case this project is not a good fit for me because I also use other libraries that require a more recent TSC.

**Comment by ENikS** [comment]
For ES5 library look at linq-es5 branch of the project. You could use install it by calling npm install linq-es5

**Comment by WouterBos** [comment]
I assume the same limitation exists for linq-es5. What is the limitation of this library to upgrade to a higher TSC? Is it a practical or a technical one?

**Comment by WouterBos** [comment]
I thought of a simpler solution: I only load the definition file like `/// <reference path="../node_modules/linq-es5/dist/linq.d.ts" />`, assuming that the definition file is less dependent on a specific version of TypeScript. But I don't know how to use it. I don't know how to get the correct type. An example would help me a lot.

My best effort so far:
```/// <reference path="../node_modules/linq-es5/dist/linq.d.ts" />

let fruits = ["apple", "mango", "orange", "passionfruit", "grape"] as Enumerable<string>; // Neither type is assignable to the other.
let result: string = fruits.FirstOrDefault();
alert(result);```

**Comment by ENikS** [comment]
You don't need to add reference to the linq-xx.d.ts file. TSC v1.8 compiler will pick its location from the package.json file. 
For sample on how to use the library please follow this link: https://tonicdev.com/eniks/using-linq
... or you could locate link on the npmjs package page saying: Try it out: "Test linq-es2015 in your browser."  and it will let you execute it in node.

**Comment by WouterBos** [comment]
Thank you very much for your help. I tried it, but apparently I still do something wrong. After some fruitless attempts I tried the project linqts and got that running. Thank you!
